### ISSUE TITLE
check-code-format.sh does not pick up .c and .h files.

### ISSUE THREAD

**Issue by chaz-browne** [LLNL/variorum#255]
*.[ch] needs to be in double quotes in order to properly include .c and .h files. Right now, the script is only checking .cpp files.

**Comment by rountree** [comment]
Reproducer code.  Put this in `variorum/scripts/test.sh`
```
#!/bin/bash

FILES1=$(find src -type f \( -name *.[ch] -o -name *.cpp \))
echo ${FILES1} | tr " " "\n" | wc -l

FILES2=$(find src -type f \( -name "*.[ch]" -o -name *.cpp \))
echo ${FILES2} | tr " " "\n" | wc -l
```

Note the `*.[ch]` is quote-escaped in the second stanza.

Run the file from the top-level variorum directory, i.e. `./scripts/test.sh`

In bash version `4.1.46(2)-release` (which we have on Quartz), the result is

```
186
186
```

When running this on bash version `5.1.4(1)-relase` the output is:
```
21
187
```

I'm not too worried about 186 versus 187.  I think we have 21 cpp files.  I'm concluding that something changed in bash 5.  Since quoting doesn't harm anything in the earlier version of bash, I'm comfortable with the fix.  (But then I would be, wouldn't I).

Thanks to @chaz-browne for help creating and running the reproducer.

**Comment by slabasan** [comment]
This is great! Thank you for this producer and for identifying this bug!

**Comment by tpatki** [comment]
Thank you so much for the reproducer -- thank you for identifying this @chaz-browne and @rountree ! Sneaky one given bash versions.
